Display categories at n+1 of the root
PrestaShop/ps_categorytree pull request #64
Opened 2022-10-28 16:25 UTC by JMauclair

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | This way you can simply display the category at the n+1 of the root which is sometimes more relevant and enable the possibility for a generalist website to specialize the category tree
| Type         |  improvement
| Deprecations | no
| How to test  |  PS 1.7.7.2, php 7.3.2.1

2022-11-08 17:08 UTC, matks requested changes
Dear @JMauclair CI is complaining, you can run `/vendor/bin/php-cs-fixer fix --dry-run` to reproduce in localhost. Can you fix the build?

2022-11-09 16:02 UTC, JMauclair commented
Hi, 

I've tried to run it but I have no php-cs-fixer in vendor/bin in local

2022-11-20 17:28 UTC, rmilecki requested changes
This `n+1` name is hard to understand and confusing for me. `n` is usually treated as any natural number, so that suggests we can have:
* (n=0): 0+1=1
* (n=1): 1+1=2
* (n=2): 2+1=3
* (n=3): 3+1=4
* ...

but you seem to only display categories of `level_depth` equal 1 and 2.

2022-11-20 17:28 UTC, rmilecki commented on ps_categorytree.php
> +                                'value' => 4,
This magic value requires its own `static::CATEGORY_ROOT_FOO` (see how other options are handled)

2022-11-20 17:28 UTC, rmilecki commented on ps_categorytree.php
> +        } elseif (Configuration::get('BLOCK_CATEG_ROOT_CATEGORY') == 4) {
Same here (`s/4/static::CATEGORY_ROOT_FOO/`)

2022-11-20 17:28 UTC, rmilecki commented on ps_categorytree.php
> +                                'label' => $this->getTranslator()->trans('Categories at n+1 of the root category', [], 'Modules.Categorytree.Admin'),
At n+1 of what exactly? Did you miss "level" word somewhere there?

2023-01-06 17:40 UTC, kpodemski commented
I thought you wanted to solve some n+1 issues, but it seems you wanted to create a new way of showing categories. I think it would be better if you could
- [create an Issue explaining what you want to achieve](https://www.prestashop-project.org/get-involved/request-features/) so the project members can validate the idea
- follow @rmilecki suggestions and respect [coding standards](https://devdocs.prestashop-project.org/8/development/coding-standards/) used in the project

If you need any help, let me know!

2023-01-29 09:11 UTC, matks commented
Hi,

Since we had no news from you for more than 3 months, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2023-01-29 09:11 UTC, closed without merging